// Claude Code integration bridge -- maps Claude activity to in-game events

import { addQuest, activeQuests, currentPhase, gameLog } from './state.js';

export function initClaudeBridge(state) {
    window._claudeBridge = {
        onFileEdit: (filePath) => {
            const name = filePath.split('/').pop() || 'file';
            triggerEvent(state, 'work', `Editing ${name.slice(0, 20)}`, 'C');
        },
        onTestRun: (passed, failed) => {
            if (failed === 0) {
                triggerEvent(state, 'study', `Tests passing (${passed})`, 'B');
            } else {
                triggerEvent(state, 'fitness', `Fix ${failed} failing test${failed > 1 ? 's' : ''}`, 'A');
            }
        },
        onCommit: (message) => {
            triggerEvent(state, 'work', `Ship: ${(message || '').slice(0, 20)}`, 'A');
            for (const c of state.colonists) {
                if (c.state !== 'dead') c.stress = Math.max(0, c.stress - 10);
            }
        },
        onTaskStart: (desc) => {
            triggerEvent(state, 'personal', (desc || 'New task').slice(0, 25), 'D');
        },
        getStatus: () => {
            const alive = state.colonists.filter(c => c.state !== 'dead');
            return {
                phase: currentPhase(state),
                alive: alive.length,
                avgLevel: alive.length ? alive.reduce((s, c) => s + c.level, 0) / alive.length : 0,
                resources: { ...state.resources },
                tick: state.currentTick,
            };
        },
    };
}

function triggerEvent(state, category, title, difficulty) {
    if (activeQuests(state).length < 5) {
        addQuest(state, { title, difficulty, category, autoGenerated: true });
    }
    gameLog(state, `Claude: ${title}`);
}
